# Михайловский Василий

### Задание 1

In [72]:
import numpy as np

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [5]:
a=np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])


In [74]:
# a=np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]]).T

In [6]:
b1=np.mean(a[:5, : 1])

In [7]:
b2=np.mean(a[:5, 1: 2])

In [8]:
mean_a=np.array([b1,b2])
print(mean_a)

[2.  8.4]


### Задание 2

In [10]:
a_centered=a-mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


### Задание 3

In [15]:
col1_a_centered=a_centered[:5,:1]
col1_a_centered

array([[-1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [-1.]])

In [56]:
col2_a_centered=a_centered[:5,1:2]
col2_a_centered



array([[-2.4],
       [-0.4],
       [ 2.6],
       [ 1.6],
       [-1.4]])

In [77]:
#a_centered_sp=col1_a_centered.T[0]@col2_a_centered.T[0]
#a_centered_sp

In [76]:
#a_centered_sp=col1_a_centered.T[0].dot(col2_a_centered.T[0])
#a_centered_sp

In [36]:
a_centered_sp=np.dot(col1_a_centered.T[0], col2_a_centered.T[0])
a_centered_sp

8.0

In [63]:
N=a.shape[0]

In [64]:
a_centered_sp/(N-1)

2.0

### Задание 4

In [69]:
covariance=np.cov(a.T)

In [70]:
covariance[0][1]

2.0